### ISSUE TITLE
doc(readme) update readme badges

### ISSUE THREAD

**Issue by S-ishita** [qascade/dcr#58]
## Description
I want to update readme badges

## Screenshots
![badges](https://github.com/qascade/dcr/assets/104543751/e9947bc2-410f-4097-8557-93c55b807b62)

## Are you raising this PR under GSSoC'23? 
Yes

## How are you planning to resolve on this issue?
Introducing few code changes in readme file

**Comment by qascade** [comment]
Hey, @S-ishita, The idea of the readme is to make sure that people understand what dcr is all about in a concise manner. Things like no. of visitors, issues, and contributions don't have meaning if they are already provided by GitHub. We may want a godoc ref, tests passing, or code coverage later down the line. But we don't want to bog down ourselves with unnecessary complications just because we added a random badge on the front page.

**Comment by qascade** [comment]
You can also look at some of other beginner-friendly issues that I have already added.
